/* Generated by bin2c, do not edit manually */
#ifndef __audio_h_included
#define __audio_h_included

/* Contents of file test_audio_input.bin */
extern const long int audio_size;
extern const unsigned char audio[1764000];

#endif    /* __audio_h_included */
