/* Generated by bin2c, do not edit manually */
#ifndef __audio_short_h_included
#define __audio_short_h_included

/* Contents of file test_audio_input.bin */
extern const long int audio_short_size;
extern const unsigned char audio_short[9376];

#endif    /* __audio_short_h_included */
